org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true

# ? ??
appName=TileMapSurvivalGame
projectVersion=0.1.0

# LibGDX ??
gdxVersion=1.12.1
gdxControllersVersion=2.2.3

# Graal Native
enableGraalNative=false
graalHelperVersion=0.4.0
